import swaggerAutogen from "swagger-autogen";
import { serve } from "swagger-ui-express";

const outputFile = "./swagger_output.json";
const endpointsFiles = ["../routes/api.ts"];

const doc = {
    info: {
        version: "v0.0.1",
        title: "Dokumentasi Express API",
        description: "Express API with autogenerated swagger doc",
    },
    servers: [
        {
            url: "http://localhost:3000/api",
            description: "Local Development server",
        },
        {
            url: "https://back-end-event-dusky.vercel.app/api",
            description: "Deploy server",
        },
    ],
    components: {
        securitySchemes: {
            bearerAuth: {
                type: "http",
                scheme: "bearer",
            },
        },
        schemas: {
            LoginRequest: {
                identifier: "Rexximo",
                password: "user123"
            },
        },
    },
};

swaggerAutogen({ openapi: "3.0.0" })(outputFile, endpointsFiles, doc);