import swaggerAutogen from "swagger-autogen";
import { serve } from "swagger-ui-express";

const outputFile = "./swagger_output.json";
const endpointsFiles = ["../routes/api.ts"];

const doc = {
    info: {
        version: "v0.0.1",
        title: "Dokumentasi Express API",
        description: "Express API with autogenerated swagger doc",
    },
    servers: [
        {
            url: "http://localhost:3000/api",
            description: "Local Development server",
        },
        {
            url: "https://back-end-event-dusky.vercel.app/api",
            description: "Deploy server",
        },
    ],
    components: {
        securitySchemes: {
            bearerAuth: {
                type: "https",
                scheme: "bearer",
            },
        },
        schemas: {
            LoginRequest: {
                identifier: "letibnuasrexximo@yopmail.com",
                password: "Rexximoo13#"
            },
            RegisterRequest: {
                fullName: "member2025",
                username: "member2025",
                email: "member2025@yopmail.com",
                password: "Member2025",
                confirmPassword: "Member2025",
            },
            ActivationRequest: {
                code: "abcdef",
            },
            CreateCategoryRequest: {
                name: "",
                description: "",
                icon: "",
            },
            CreateEventRequest: {
                "name": "",
                "banner": "",
                "category": "category ObjectID",
                "description": "",
                "startDate": "yyyy-mm-dd hh:mm:ss",
                "endDate": "yyyy-mm-dd hh:mm:ss",
                "location": {
                    "region": "region id",
                    "coordinates": [0, 0],
                },
                "isOnline": true,
                "isFeatured": true
            },
            RemoveMediaRequest: {
                fileUrl: "",
            },
        },
    },
};

swaggerAutogen({ openapi: "3.0.0" })(outputFile, endpointsFiles, doc);